config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  resources :items do
    collection do
      get 'next_day'
      get 'toggle_drunk_mode'
    end  
  end
end

app/models/aged_brie.rb
class AgedBrie < Item
  def set_quantity
    self.quality = quality + 1 if quality < MAX_QUALITY
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/backstage.rb
class Backstage < Item
  def set_quantity
    if self.quality < 50
      case sell_in
      when -Float::INFINITY...0
        self.quality = self.quality = 0
      when 10...Float::INFINITY
        self.quality = self.quality + 1
      when 6...10
        self.quality = self.quality + 2
      when 1...5
        self.quality = self.quality + 3
      end
    end
  end
end

app/models/conjured.rb
class Conjured < Item
  def set_quantity
    self.quality = quality - 2
  end
end

app/models/item.rb
class Item < ApplicationRecord
  attr_reader :drunk_mode
  validates :name, presence: true
  validates :sell_in, presence: true
  validates :quality, presence: true

  MAX_QUALITY = 50

   def next_day(price_calculator = Items::PriceCalculatorService.new)
    self.sell_in = sell_in - 1
    set_quantity if quality > 0
    self.price = price_calculator.(value: price) if sell_in < 0 
  end

   def next_day!
    next_day
    save!
  end

  def set_quantity
    if sell_in < 0
      self.quality = quality - 2
    else
      self.quality = quality - 1 
    end
  end
end

app/models/sulfuras.rb
class Sulfuras < Item
  def next_day; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    @items = decorate_items(items: @items) if session[:drunk_mode]
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def next_day
  #   Item.all.each do |item|
  #     if item.name != "Aged Brie" and item.name != "Backstage passes to a TAFKAL80ETC concert"
  #       if item.quality > 0
  #         if item.name != "Sulfuras, Hand of Ragnaros"
  #           item.quality = item.quality - 1
  #         end
  #       end
  #     else
  #       if item.quality < 50
  #         item.quality = item.quality + 1
  #         if item.name == "Backstage passes to a TAFKAL80ETC concert"
  #           if item.sell_in < 11
  #             if item.quality < 50
  #               item.quality = item.quality + 1
  #             end
  #           end
  #           if item.sell_in < 6
  #             if item.quality < 50
  #               item.quality = item.quality + 1
  #             end
  #           end
  #         end
  #       end
  #     end
  #     if item.name != "Sulfuras, Hand of Ragnaros"
  #       item.sell_in = item.sell_in - 1
  #     end
  #     if item.sell_in < 0
  #       if item.name != "Aged Brie"
  #         if item.name != "Backstage passes to a TAFKAL80ETC concert"
  #           if item.quality > 0
  #             if item.name != "Sulfuras, Hand of Ragnaros"
  #               item.quality = item.quality - 1
  #             end
  #           end
  #         else
  #           item.quality = item.quality - item.quality
  #         end
  #       else
  #         if item.quality < 50
  #           item.quality = item.quality + 1
  #         end
  #       end
  #     end
  #     item.save
  #   end
  #   redirect_to root_path
  # end

  def next_day
    Items::NextDayService.new.(items: Item.all)
    redirect_to root_path
  end

  def toggle_drunk_mode
    session[:drunk_mode] = !!!session[:drunk_mode]
    redirect_to root_path
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:name, :sell_in, :quality)
  end

  def decorate_items(items:)
    items.each { |item| item.extend(Items::DrunkModeDecorator) }
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
  
  def next_day
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper

  def decorate_item(item)
    item.extends(Items::DrunkModeDecorator)
  end
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :sell_in %>
    <%= form.number_field :sell_in %>
  </div>

  <div class="field">
    <%= form.label :quality %>
    <%= form.number_field :quality %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sell in</th>
      <th>Quality</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.sell_in %></td>
        <td><%= item.quality %></td>
        <td><%= link_to 'Show', item_path(item) %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item_path(item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>
<%= link_to 'Next Day', next_day_items_path(drunk_mode: params[:drunk_mode]) %>
<%= link_to 'Drunk mode', toggle_drunk_mode_items_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Sell in:</strong>
  <%= @item.sell_in %>
</p>

<p>
  <strong>Quality:</strong>
  <%= @item.quality %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalExercice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page/index.html.erb
<h1>Page#index</h1>
<p>Find me in app/views/page/index.html.erb</p>